
package com.yogesh;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://yogesh.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://yogesh.com/", className = "com.yogesh.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://yogesh.com/", className = "com.yogesh.AddResponse")
    @Action(input = "http://yogesh.com/Calculator/addRequest", output = "http://yogesh.com/Calculator/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sub", targetNamespace = "http://yogesh.com/", className = "com.yogesh.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://yogesh.com/", className = "com.yogesh.SubResponse")
    @Action(input = "http://yogesh.com/Calculator/subRequest", output = "http://yogesh.com/Calculator/subResponse")
    public int sub(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mul", targetNamespace = "http://yogesh.com/", className = "com.yogesh.Mul")
    @ResponseWrapper(localName = "mulResponse", targetNamespace = "http://yogesh.com/", className = "com.yogesh.MulResponse")
    @Action(input = "http://yogesh.com/Calculator/mulRequest", output = "http://yogesh.com/Calculator/mulResponse")
    public int mul(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "div", targetNamespace = "http://yogesh.com/", className = "com.yogesh.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://yogesh.com/", className = "com.yogesh.DivResponse")
    @Action(input = "http://yogesh.com/Calculator/divRequest", output = "http://yogesh.com/Calculator/divResponse")
    public int div(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
